# Generated by Django 5.0 on 2025-02-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageurl', models.CharField(max_length=255)),
            ],
        ),
    ]
