# Generated by Django 5.1.5 on 2025-02-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("imageUrl", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
